function runAnimations() {
  document
    .querySelector("#id-196")
    .addEventListener("mouseenter", func_hover_196_67211);

  function func_hover_196_67211(e) {
    e.stopPropagation();
    function func_196_67211(e) {
      e.stopPropagation();

      document
        .querySelector(".parent-div")
        .classList.add("parent-animation-411");
      document.querySelector("#id-411").classList.add("animationClass-411");
      document.querySelector("#id-195").classList.add("animationClass-195");
      document
        .querySelector("#id-195 > div:first-child")
        .classList.add("bgClass-67219");
      document
        .querySelector(".scott-1-338985-0")
        .classList.add("animationClass-825-825-0");
      document.querySelector("#id-825").classList.add("animationClass-825");
      document
        .querySelector(".travis-1-357492-0")
        .classList.add("animationClass-824-824-0");
      document.querySelector("#id-824").classList.add("animationClass-824");
      document
        .querySelector(".title-1-362544-0")
        .classList.add("animationClass-42-42-0");
      document.querySelector("#id-42").classList.add("animationClass-42");
      document.querySelector("#id-731").classList.add("animationClass-731");
      document.querySelector("#id-423").classList.add("animationClass-423");
      document.querySelector("#id-417").classList.add("animationClass-417");
      document.querySelector("#id-418").classList.add("animationClass-418");
      document.querySelector("#id-196").classList.add("animationClass-196");
      document.querySelector("#id-5073").classList.add("nullAnimation-5073");
      document.querySelector("#id-142").classList.add("animationClass-142");
      document.querySelector("#id-143").classList.add("animationClass-143");
      document.querySelector("#id-144").classList.add("nullAnimation-144");
      document.querySelector("#id-5074").classList.add("nullAnimation-5074");
      document.querySelector("#id-5075").classList.add("nullAnimation-5075");
      document.querySelector("#id-10827").classList.add("nullAnimation-10827");
      document.querySelector("#id-5072").classList.add("nullAnimation-5072");
      document.querySelector("#id-144").classList.add("animationClass-144");
      document.querySelector("#id-198").classList.add("animationClass-198");
      document.querySelector("#id-734").classList.add("animationClass-734");
      document
        .querySelector(".listen-1-416936-0")
        .classList.add("animationClass-172-172-0");
      document.querySelector("#id-172").classList.add("animationClass-172");
      document.querySelector("#id-11248").classList.add("animationClass-11248");
      document
        .querySelector(".connect-1-36309-0")
        .classList.add("animationClass-11247-11247-0");
      document.querySelector("#id-11247").classList.add("animationClass-11247");
      document
        .querySelector("#id-196")
        .removeEventListener("mouseenter", func_hover_196_67211);

      document
        .querySelector("#id-196")
        .addEventListener("mouseout", func_exit_196_67211);
    }

    function func_exit_196_67211(e) {
      e.stopPropagation();
      document
        .querySelector(".parent-div")
        .classList.add("parent-animation-rev-67211");
      document
        .querySelector("#id-411")
        .classList.add("animationClassBack-67211");
      document
        .querySelector("#id-195")
        .classList.add("animationClassBack-67219");
      document
        .querySelector("#id-195 > div:first-child")
        .classList.add("bgClassBack-195");
      document
        .querySelector("#id-825")
        .classList.add("animationClassBack-67212");
      document
        .querySelector("#id-824")
        .classList.add("animationClassBack-67213");
      document
        .querySelector("#id-42")
        .classList.add("animationClassBack-67218");
      document
        .querySelector("#id-731")
        .classList.add("animationClassBack-67216");
      document
        .querySelector("#id-423")
        .classList.add("animationClassBack-67217");
      document
        .querySelector("#id-417")
        .classList.add("animationClassBack-67214");
      document
        .querySelector("#id-418")
        .classList.add("animationClassBack-67215");
      document
        .querySelector("#id-196")
        .classList.add("animationClassBack-67220");
      document.querySelector("#id-5073").classList.add("nullAnimation-5073");
      document
        .querySelector("#id-142")
        .classList.add("animationClassBack-67221");
      document
        .querySelector("#id-143")
        .classList.add("animationClassBack-67222");
      document.querySelector("#id-144").classList.add("nullAnimation-144");
      document.querySelector("#id-5074").classList.add("nullAnimation-5074");
      document.querySelector("#id-5075").classList.add("nullAnimation-5075");
      document.querySelector("#id-10827").classList.add("nullAnimation-10827");
      document.querySelector("#id-5072").classList.add("nullAnimation-5072");
      document
        .querySelector("#id-144")
        .classList.add("animationClassBack-67223");
      document
        .querySelector("#id-198")
        .classList.add("animationClassBack-138511");
      document
        .querySelector("#id-734")
        .classList.add("animationClassBack-138512");
      document
        .querySelector("#id-172")
        .classList.add("animationClassBack-138513");
      document
        .querySelector("#id-11248")
        .classList.add("animationClassBack-12326");
      document
        .querySelector("#id-11247")
        .classList.add("animationClassBack-12327");
      document
        .querySelector("#id-196")
        .removeEventListener("mouseout", func_exit_196_67211);
      setTimeout(() => {
        document
          .querySelector(".parent-div")
          .classList.remove("parent-animation-411");
        document
          .querySelector("#id-411")
          .classList.remove("animationClass-411");
        document
          .querySelector("#id-195")
          .classList.remove("animationClass-195");
        document
          .querySelector("#id-195 > div:first-child")
          .classList.remove("bgClass-67219");
        document
          .querySelector(".scott-1-338985-0")
          .classList.remove("animationClass-825-825-0");
        document
          .querySelector("#id-825")
          .classList.remove("animationClass-825");
        document
          .querySelector(".travis-1-357492-0")
          .classList.remove("animationClass-824-824-0");
        document
          .querySelector("#id-824")
          .classList.remove("animationClass-824");
        document
          .querySelector(".title-1-362544-0")
          .classList.remove("animationClass-42-42-0");
        document.querySelector("#id-42").classList.remove("animationClass-42");
        document
          .querySelector("#id-731")
          .classList.remove("animationClass-731");
        document
          .querySelector("#id-423")
          .classList.remove("animationClass-423");
        document
          .querySelector("#id-417")
          .classList.remove("animationClass-417");
        document
          .querySelector("#id-418")
          .classList.remove("animationClass-418");
        document
          .querySelector("#id-196")
          .classList.remove("animationClass-196");
        document
          .querySelector("#id-5073")
          .classList.remove("nullAnimation-5073");
        document
          .querySelector("#id-142")
          .classList.remove("animationClass-142");
        document
          .querySelector("#id-143")
          .classList.remove("animationClass-143");
        document.querySelector("#id-144").classList.remove("nullAnimation-144");
        document
          .querySelector("#id-5074")
          .classList.remove("nullAnimation-5074");
        document
          .querySelector("#id-5075")
          .classList.remove("nullAnimation-5075");
        document
          .querySelector("#id-10827")
          .classList.remove("nullAnimation-10827");
        document
          .querySelector("#id-5072")
          .classList.remove("nullAnimation-5072");
        document
          .querySelector("#id-144")
          .classList.remove("animationClass-144");
        document
          .querySelector("#id-198")
          .classList.remove("animationClass-198");
        document
          .querySelector("#id-734")
          .classList.remove("animationClass-734");
        document
          .querySelector(".listen-1-416936-0")
          .classList.remove("animationClass-172-172-0");
        document
          .querySelector("#id-172")
          .classList.remove("animationClass-172");
        document
          .querySelector("#id-11248")
          .classList.remove("animationClass-11248");
        document
          .querySelector(".connect-1-36309-0")
          .classList.remove("animationClass-11247-11247-0");
        document
          .querySelector("#id-11247")
          .classList.remove("animationClass-11247");
        document
          .querySelector(".parent-div")
          .classList.remove("parent-animation-rev-67211");
        document
          .querySelector("#id-411")
          .classList.remove("animationClassBack-67211");
        document
          .querySelector("#id-195")
          .classList.remove("animationClassBack-67219");
        document
          .querySelector("#id-195 > div:first-child")
          .classList.remove("bgClassBack-195");
        document
          .querySelector("#id-825")
          .classList.remove("animationClassBack-67212");
        document
          .querySelector("#id-824")
          .classList.remove("animationClassBack-67213");
        document
          .querySelector("#id-42")
          .classList.remove("animationClassBack-67218");
        document
          .querySelector("#id-731")
          .classList.remove("animationClassBack-67216");
        document
          .querySelector("#id-423")
          .classList.remove("animationClassBack-67217");
        document
          .querySelector("#id-417")
          .classList.remove("animationClassBack-67214");
        document
          .querySelector("#id-418")
          .classList.remove("animationClassBack-67215");
        document
          .querySelector("#id-196")
          .classList.remove("animationClassBack-67220");
        document
          .querySelector("#id-5073")
          .classList.remove("nullAnimation-5073");
        document
          .querySelector("#id-142")
          .classList.remove("animationClassBack-67221");
        document
          .querySelector("#id-143")
          .classList.remove("animationClassBack-67222");
        document.querySelector("#id-144").classList.remove("nullAnimation-144");
        document
          .querySelector("#id-5074")
          .classList.remove("nullAnimation-5074");
        document
          .querySelector("#id-5075")
          .classList.remove("nullAnimation-5075");
        document
          .querySelector("#id-10827")
          .classList.remove("nullAnimation-10827");
        document
          .querySelector("#id-5072")
          .classList.remove("nullAnimation-5072");
        document
          .querySelector("#id-144")
          .classList.remove("animationClassBack-67223");
        document
          .querySelector("#id-198")
          .classList.remove("animationClassBack-138511");
        document
          .querySelector("#id-734")
          .classList.remove("animationClassBack-138512");
        document
          .querySelector("#id-172")
          .classList.remove("animationClassBack-138513");
        document
          .querySelector("#id-11248")
          .classList.remove("animationClassBack-12326");
        document
          .querySelector("#id-11247")
          .classList.remove("animationClassBack-12327");
        document
          .querySelector("#id-196")
          .addEventListener("mouseenter", func_hover_196_67211);
      }, 1000);
    }
    func_196_67211();

    setTimeout(() => {
      document
        .querySelector("#id-196")
        .addEventListener("mouseenter", func_196_5055);
    }, 100);
  }

  function func_hover_196_5055(e) {
    e.stopPropagation();
    function func_196_5055(e) {
      e.stopPropagation();
      document
        .querySelector("#id-196")
        .removeEventListener("mouseenter", func_hover_196_67211);

      document
        .querySelector(".parent-div")
        .classList.add("parent-animation-67211");
      document.querySelector("#id-411").classList.add("animationClass-67211");
      document.querySelector("#id-195").classList.add("animationClass-67219");
      document
        .querySelector("#id-195 > div:first-child")
        .classList.add("bgClass-5063");
      document
        .querySelector(".scott-1-338985-0")
        .classList.add("animationClass-67212-67212-0");
      document.querySelector("#id-825").classList.add("animationClass-67212");
      document
        .querySelector(".travis-1-357492-0")
        .classList.add("animationClass-67213-67213-0");
      document.querySelector("#id-824").classList.add("animationClass-67213");
      document
        .querySelector(".title-1-362544-0")
        .classList.add("animationClass-67218-67218-0");
      document.querySelector("#id-42").classList.add("animationClass-67218");
      document.querySelector("#id-731").classList.add("animationClass-67216");
      document.querySelector("#id-423").classList.add("animationClass-67217");
      document.querySelector("#id-417").classList.add("animationClass-67214");
      document.querySelector("#id-418").classList.add("animationClass-67215");
      document.querySelector("#id-196").classList.add("animationClass-67220");
      document
        .querySelector("#id-5073")
        .classList.add("animationClass-null5073");
      document.querySelector("#id-142").classList.add("animationClass-67221");
      document.querySelector("#id-143").classList.add("animationClass-67222");
      document
        .querySelector("#id-5074")
        .classList.add("animationClass-null5074");
      document
        .querySelector("#id-5075")
        .classList.add("animationClass-null5075");
      document
        .querySelector("#id-10827")
        .classList.add("animationClass-null10827");
      document
        .querySelector("#id-5072")
        .classList.add("animationClass-null5072");
      document.querySelector("#id-144").classList.add("animationClass-67223");
      document.querySelector("#id-198").classList.add("animationClass-138511");
      document.querySelector("#id-734").classList.add("animationClass-138512");
      document
        .querySelector(".listen-1-416936-0")
        .classList.add("animationClass-138513-138513-0");
      document.querySelector("#id-172").classList.add("animationClass-138513");
      document.querySelector("#id-11248").classList.add("animationClass-12326");
      document
        .querySelector(".connect-1-36309-0")
        .classList.add("animationClass-12327-12327-0");
      document.querySelector("#id-11247").classList.add("animationClass-12327");
      document
        .querySelector("#id-196")
        .removeEventListener("mouseenter", func_hover_196_5055);

      document
        .querySelector("#id-196")
        .addEventListener("mouseout", func_exit_196_5055);
    }

    function func_exit_196_5055(e) {
      e.stopPropagation();
      document
        .querySelector(".parent-div")
        .classList.add("parent-animation-rev-5055");
      document
        .querySelector("#id-411")
        .classList.add("animationClassBack-5055");
      document
        .querySelector("#id-195")
        .classList.add("animationClassBack-5063");
      document
        .querySelector("#id-195 > div:first-child")
        .classList.add("bgClassBack-67219");
      document
        .querySelector("#id-825")
        .classList.add("animationClassBack-5056");
      document
        .querySelector("#id-824")
        .classList.add("animationClassBack-5057");
      document.querySelector("#id-42").classList.add("animationClassBack-5062");
      document
        .querySelector("#id-731")
        .classList.add("animationClassBack-5060");
      document
        .querySelector("#id-423")
        .classList.add("animationClassBack-5061");
      document
        .querySelector("#id-417")
        .classList.add("animationClassBack-5058");
      document
        .querySelector("#id-418")
        .classList.add("animationClassBack-5059");
      document
        .querySelector("#id-196")
        .classList.add("animationClassBack-5064");
      document
        .querySelector("#id-5073")
        .classList.add("animationClassBack-5073");
      document
        .querySelector("#id-142")
        .classList.add("animationClassBack-5065");
      document
        .querySelector("#id-143")
        .classList.add("animationClassBack-null67222");
      document
        .querySelector("#id-5074")
        .classList.add("animationClassBack-5074");
      document
        .querySelector("#id-5075")
        .classList.add("animationClassBack-5075");
      document
        .querySelector("#id-10827")
        .classList.add("animationClassBack-10827");
      document
        .querySelector("#id-5072")
        .classList.add("animationClassBack-5072");
      document
        .querySelector("#id-144")
        .classList.add("animationClassBack-5067");
      document
        .querySelector("#id-198")
        .classList.add("animationClassBack-138514");
      document
        .querySelector("#id-734")
        .classList.add("animationClassBack-138515");
      document
        .querySelector("#id-172")
        .classList.add("animationClassBack-138516");
      document
        .querySelector("#id-11248")
        .classList.add("animationClassBack-12340");
      document
        .querySelector("#id-11247")
        .classList.add("animationClassBack-12341");
      document
        .querySelector("#id-196")
        .removeEventListener("mouseout", func_exit_196_5055);
      setTimeout(() => {
        document
          .querySelector(".parent-div")
          .classList.remove("parent-animation-67211");
        document
          .querySelector("#id-411")
          .classList.remove("animationClass-67211");
        document
          .querySelector("#id-195")
          .classList.remove("animationClass-67219");
        document
          .querySelector("#id-195 > div:first-child")
          .classList.remove("bgClass-5063");
        document
          .querySelector(".scott-1-338985-0")
          .classList.remove("animationClass-67212-67212-0");
        document
          .querySelector("#id-825")
          .classList.remove("animationClass-67212");
        document
          .querySelector(".travis-1-357492-0")
          .classList.remove("animationClass-67213-67213-0");
        document
          .querySelector("#id-824")
          .classList.remove("animationClass-67213");
        document
          .querySelector(".title-1-362544-0")
          .classList.remove("animationClass-67218-67218-0");
        document
          .querySelector("#id-42")
          .classList.remove("animationClass-67218");
        document
          .querySelector("#id-731")
          .classList.remove("animationClass-67216");
        document
          .querySelector("#id-423")
          .classList.remove("animationClass-67217");
        document
          .querySelector("#id-417")
          .classList.remove("animationClass-67214");
        document
          .querySelector("#id-418")
          .classList.remove("animationClass-67215");
        document
          .querySelector("#id-196")
          .classList.remove("animationClass-67220");
        document
          .querySelector("#id-5073")
          .classList.remove("animationClass-null5073");
        document
          .querySelector("#id-142")
          .classList.remove("animationClass-67221");
        document
          .querySelector("#id-143")
          .classList.remove("animationClass-67222");
        document
          .querySelector("#id-5074")
          .classList.remove("animationClass-null5074");
        document
          .querySelector("#id-5075")
          .classList.remove("animationClass-null5075");
        document
          .querySelector("#id-10827")
          .classList.remove("animationClass-null10827");
        document
          .querySelector("#id-5072")
          .classList.remove("animationClass-null5072");
        document
          .querySelector("#id-144")
          .classList.remove("animationClass-67223");
        document
          .querySelector("#id-198")
          .classList.remove("animationClass-138511");
        document
          .querySelector("#id-734")
          .classList.remove("animationClass-138512");
        document
          .querySelector(".listen-1-416936-0")
          .classList.remove("animationClass-138513-138513-0");
        document
          .querySelector("#id-172")
          .classList.remove("animationClass-138513");
        document
          .querySelector("#id-11248")
          .classList.remove("animationClass-12326");
        document
          .querySelector(".connect-1-36309-0")
          .classList.remove("animationClass-12327-12327-0");
        document
          .querySelector("#id-11247")
          .classList.remove("animationClass-12327");
        document
          .querySelector(".parent-div")
          .classList.remove("parent-animation-rev-5055");
        document
          .querySelector("#id-411")
          .classList.remove("animationClassBack-5055");
        document
          .querySelector("#id-195")
          .classList.remove("animationClassBack-5063");
        document
          .querySelector("#id-195 > div:first-child")
          .classList.remove("bgClassBack-67219");
        document
          .querySelector("#id-825")
          .classList.remove("animationClassBack-5056");
        document
          .querySelector("#id-824")
          .classList.remove("animationClassBack-5057");
        document
          .querySelector("#id-42")
          .classList.remove("animationClassBack-5062");
        document
          .querySelector("#id-731")
          .classList.remove("animationClassBack-5060");
        document
          .querySelector("#id-423")
          .classList.remove("animationClassBack-5061");
        document
          .querySelector("#id-417")
          .classList.remove("animationClassBack-5058");
        document
          .querySelector("#id-418")
          .classList.remove("animationClassBack-5059");
        document
          .querySelector("#id-196")
          .classList.remove("animationClassBack-5064");
        document
          .querySelector("#id-5073")
          .classList.remove("animationClassBack-5073");
        document
          .querySelector("#id-142")
          .classList.remove("animationClassBack-5065");
        document
          .querySelector("#id-143")
          .classList.remove("animationClassBack-null67222");
        document
          .querySelector("#id-5074")
          .classList.remove("animationClassBack-5074");
        document
          .querySelector("#id-5075")
          .classList.remove("animationClassBack-5075");
        document
          .querySelector("#id-10827")
          .classList.remove("animationClassBack-10827");
        document
          .querySelector("#id-5072")
          .classList.remove("animationClassBack-5072");
        document
          .querySelector("#id-144")
          .classList.remove("animationClassBack-5067");
        document
          .querySelector("#id-198")
          .classList.remove("animationClassBack-138514");
        document
          .querySelector("#id-734")
          .classList.remove("animationClassBack-138515");
        document
          .querySelector("#id-172")
          .classList.remove("animationClassBack-138516");
        document
          .querySelector("#id-11248")
          .classList.remove("animationClassBack-12340");
        document
          .querySelector("#id-11247")
          .classList.remove("animationClassBack-12341");
        document
          .querySelector("#id-196")
          .addEventListener("mouseenter", func_hover_196_5055);
      }, 500);
    }
    func_196_5055();

    setTimeout(() => {
      document.querySelector("#id-196").addEventListener("click", func_196_411);
    }, 100);
  }

  function func_196_411(e) {
    e.stopPropagation();
    document
      .querySelector("#id-196")
      .removeEventListener("mouseenter", func_hover_196_5055);

    document
      .querySelector(".parent-div")
      .classList.add("parent-animation-5055");
    document.querySelector("#id-411").classList.add("animationClass-5055");
    document.querySelector("#id-195").classList.add("animationClass-5063");
    document
      .querySelector("#id-195 > div:first-child")
      .classList.add("bgClass-195");
    document
      .querySelector(".scott-1-338985-0")
      .classList.add("animationClass-5056-5056-0");
    document.querySelector("#id-825").classList.add("animationClass-5056");
    document
      .querySelector(".travis-1-357492-0")
      .classList.add("animationClass-5057-5057-0");
    document.querySelector("#id-824").classList.add("animationClass-5057");
    document
      .querySelector(".title-1-362544-0")
      .classList.add("animationClass-5062-5062-0");
    document.querySelector("#id-42").classList.add("animationClass-5062");
    document.querySelector("#id-731").classList.add("animationClass-5060");
    document.querySelector("#id-423").classList.add("animationClass-5061");
    document.querySelector("#id-417").classList.add("animationClass-5058");
    document.querySelector("#id-418").classList.add("animationClass-5059");
    document.querySelector("#id-196").classList.add("animationClass-5064");
    document.querySelector("#id-5073").classList.add("animationClass-5073");
    document.querySelector("#id-142").classList.add("animationClass-5065");
    document.querySelector("#id-143").classList.add("animationClass-null143");
    document.querySelector("#id-144").classList.add("animationClass-null144");
    document.querySelector("#id-5074").classList.add("animationClass-5074");
    document.querySelector("#id-5075").classList.add("animationClass-5075");
    document.querySelector("#id-10827").classList.add("animationClass-10827");
    document.querySelector("#id-5072").classList.add("animationClass-5072");
    document.querySelector("#id-198").classList.add("animationClass-138514");
    document.querySelector("#id-734").classList.add("animationClass-138515");
    document
      .querySelector(".listen-1-416936-0")
      .classList.add("animationClass-138516-138516-0");
    document.querySelector("#id-172").classList.add("animationClass-138516");
    document.querySelector("#id-11248").classList.add("animationClass-12340");
    document
      .querySelector(".connect-1-36309-0")
      .classList.add("animationClass-12341-12341-0");
    document.querySelector("#id-11247").classList.add("animationClass-12341");
    document
      .querySelector("#id-196")
      .removeEventListener("click", func_196_411);

    setTimeout(() => {
      //loop login
      document
        .querySelector(".parent-div")
        .classList.remove("parent-animation-411");
      document.querySelector("#id-411").classList.remove("animationClass-411");
      document.querySelector("#id-195").classList.remove("animationClass-195");
      document
        .querySelector("#id-195 > div:first-child")
        .classList.remove("bgClass-67219");
      document
        .querySelector(".scott-1-338985-0")
        .classList.remove("animationClass-825-825-0");
      document.querySelector("#id-825").classList.remove("animationClass-825");
      document
        .querySelector(".travis-1-357492-0")
        .classList.remove("animationClass-824-824-0");
      document.querySelector("#id-824").classList.remove("animationClass-824");
      document
        .querySelector(".title-1-362544-0")
        .classList.remove("animationClass-42-42-0");
      document.querySelector("#id-42").classList.remove("animationClass-42");
      document.querySelector("#id-731").classList.remove("animationClass-731");
      document.querySelector("#id-423").classList.remove("animationClass-423");
      document.querySelector("#id-417").classList.remove("animationClass-417");
      document.querySelector("#id-418").classList.remove("animationClass-418");
      document.querySelector("#id-196").classList.remove("animationClass-196");
      document.querySelector("#id-5073").classList.remove("nullAnimation-5073");
      document.querySelector("#id-142").classList.remove("animationClass-142");
      document.querySelector("#id-143").classList.remove("animationClass-143");
      document.querySelector("#id-144").classList.remove("nullAnimation-144");
      document.querySelector("#id-5074").classList.remove("nullAnimation-5074");
      document.querySelector("#id-5075").classList.remove("nullAnimation-5075");
      document
        .querySelector("#id-10827")
        .classList.remove("nullAnimation-10827");
      document.querySelector("#id-5072").classList.remove("nullAnimation-5072");
      document.querySelector("#id-144").classList.remove("animationClass-144");
      document.querySelector("#id-198").classList.remove("animationClass-198");
      document.querySelector("#id-734").classList.remove("animationClass-734");
      document
        .querySelector(".listen-1-416936-0")
        .classList.remove("animationClass-172-172-0");
      document.querySelector("#id-172").classList.remove("animationClass-172");
      document
        .querySelector("#id-11248")
        .classList.remove("animationClass-11248");
      document
        .querySelector(".connect-1-36309-0")
        .classList.remove("animationClass-11247-11247-0");
      document
        .querySelector("#id-11247")
        .classList.remove("animationClass-11247");
      document
        .querySelector(".parent-div")
        .classList.remove("parent-animation-67211");
      document
        .querySelector("#id-411")
        .classList.remove("animationClass-67211");
      document
        .querySelector("#id-195")
        .classList.remove("animationClass-67219");
      document
        .querySelector("#id-195 > div:first-child")
        .classList.remove("bgClass-5063");
      document
        .querySelector(".scott-1-338985-0")
        .classList.remove("animationClass-67212-67212-0");
      document
        .querySelector("#id-825")
        .classList.remove("animationClass-67212");
      document
        .querySelector(".travis-1-357492-0")
        .classList.remove("animationClass-67213-67213-0");
      document
        .querySelector("#id-824")
        .classList.remove("animationClass-67213");
      document
        .querySelector(".title-1-362544-0")
        .classList.remove("animationClass-67218-67218-0");
      document.querySelector("#id-42").classList.remove("animationClass-67218");
      document
        .querySelector("#id-731")
        .classList.remove("animationClass-67216");
      document
        .querySelector("#id-423")
        .classList.remove("animationClass-67217");
      document
        .querySelector("#id-417")
        .classList.remove("animationClass-67214");
      document
        .querySelector("#id-418")
        .classList.remove("animationClass-67215");
      document
        .querySelector("#id-196")
        .classList.remove("animationClass-67220");
      document
        .querySelector("#id-5073")
        .classList.remove("animationClass-null5073");
      document
        .querySelector("#id-142")
        .classList.remove("animationClass-67221");
      document
        .querySelector("#id-143")
        .classList.remove("animationClass-67222");
      document
        .querySelector("#id-5074")
        .classList.remove("animationClass-null5074");
      document
        .querySelector("#id-5075")
        .classList.remove("animationClass-null5075");
      document
        .querySelector("#id-10827")
        .classList.remove("animationClass-null10827");
      document
        .querySelector("#id-5072")
        .classList.remove("animationClass-null5072");
      document
        .querySelector("#id-144")
        .classList.remove("animationClass-67223");
      document
        .querySelector("#id-198")
        .classList.remove("animationClass-138511");
      document
        .querySelector("#id-734")
        .classList.remove("animationClass-138512");
      document
        .querySelector(".listen-1-416936-0")
        .classList.remove("animationClass-138513-138513-0");
      document
        .querySelector("#id-172")
        .classList.remove("animationClass-138513");
      document
        .querySelector("#id-11248")
        .classList.remove("animationClass-12326");
      document
        .querySelector(".connect-1-36309-0")
        .classList.remove("animationClass-12327-12327-0");
      document
        .querySelector("#id-11247")
        .classList.remove("animationClass-12327");
      document
        .querySelector(".parent-div")
        .classList.remove("parent-animation-5055");
      document.querySelector("#id-411").classList.remove("animationClass-5055");
      document.querySelector("#id-195").classList.remove("animationClass-5063");
      document
        .querySelector("#id-195 > div:first-child")
        .classList.remove("bgClass-195");
      document
        .querySelector(".scott-1-338985-0")
        .classList.remove("animationClass-5056-5056-0");
      document.querySelector("#id-825").classList.remove("animationClass-5056");
      document
        .querySelector(".travis-1-357492-0")
        .classList.remove("animationClass-5057-5057-0");
      document.querySelector("#id-824").classList.remove("animationClass-5057");
      document
        .querySelector(".title-1-362544-0")
        .classList.remove("animationClass-5062-5062-0");
      document.querySelector("#id-42").classList.remove("animationClass-5062");
      document.querySelector("#id-731").classList.remove("animationClass-5060");
      document.querySelector("#id-423").classList.remove("animationClass-5061");
      document.querySelector("#id-417").classList.remove("animationClass-5058");
      document.querySelector("#id-418").classList.remove("animationClass-5059");
      document.querySelector("#id-196").classList.remove("animationClass-5064");
      document
        .querySelector("#id-5073")
        .classList.remove("animationClass-5073");
      document.querySelector("#id-142").classList.remove("animationClass-5065");
      document
        .querySelector("#id-143")
        .classList.remove("animationClass-null143");
      document
        .querySelector("#id-144")
        .classList.remove("animationClass-null144");
      document
        .querySelector("#id-5074")
        .classList.remove("animationClass-5074");
      document
        .querySelector("#id-5075")
        .classList.remove("animationClass-5075");
      document
        .querySelector("#id-10827")
        .classList.remove("animationClass-10827");
      document
        .querySelector("#id-5072")
        .classList.remove("animationClass-5072");
      document
        .querySelector("#id-198")
        .classList.remove("animationClass-138514");
      document
        .querySelector("#id-734")
        .classList.remove("animationClass-138515");
      document
        .querySelector(".listen-1-416936-0")
        .classList.remove("animationClass-138516-138516-0");
      document
        .querySelector("#id-172")
        .classList.remove("animationClass-138516");
      document
        .querySelector("#id-11248")
        .classList.remove("animationClass-12340");
      document
        .querySelector(".connect-1-36309-0")
        .classList.remove("animationClass-12341-12341-0");
      document
        .querySelector("#id-11247")
        .classList.remove("animationClass-12341");
      runAnimations();
    }, 500);
  }
}
runAnimations();
